name = "LambertsProblem"
uuid = "bfcf449f-4a4c-42e3-91d7-977e7d435437"
authors = ["Burton Yale <burtonyale@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = ">=1.9"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[project]
repo = "https://github.com/Burtony3/LambertsProblem.jl"

[targets]
test = ["Test"]
