name = "LambertsProblem"
uuid = "bfcf449f-4a4c-42e3-91d7-977e7d435437"
authors = ["Burton Yale <burtonyale@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
